### ISSUE TITLE
Set up Nginx Server 

### ISSUE THREAD

**Issue by davidkroodsma** [GlobalFishingWatch/pybossa-vessel-identification#1]
We need to set up a Nginx server to deploy Pybossa instead of the current way we are making it visible (http://104.197.198.109:5000/)

The instructions for installing Pybossa on Google Cloud virtual machines, which are what I followed step by step, are in the file 
[Installing_Pybossa.md](https://github.com/GlobalFishingWatch/pybossa-vessel-identification/blob/master/Instaling_Pybossa.md)

Here are the instructions on Pybossa's website for "Deploying Pybossa with nginix and uwsgi": 
http://docs.pybossa.com/en/latest/nginx.html

**Comment by enriquetuya** [comment]
This is done, you can now request directly to: 
http://104.197.198.109:5000/
http://104.197.198.109/

Updated documentation here:
https://github.com/GlobalFishingWatch/pybossa-vessel-identification/blob/master/Instaling_Pybossa.md

@davidkroodsma please test everything on http://104.197.198.109, if it looks good let's close this ticket and configure the proper DNS.
