### ISSUE TITLE
Extract Results from id_fishing_points

### ISSUE THREAD

**Issue by davidkroodsma** [GlobalFishingWatch/pybossa-vessel-identification#3]
We need to figure out how to take the results from this project and put them in a format that is useful for the machine learning team.

This will involve figuring out how to compare results between users, and also line the results up with the original AIS messages.

The tasks and tasks runs can be downloaded using the download_results.py file in the results folder.

**Comment by redhog** [comment]
@enriquetuya What is the priority of this?

**Comment by davidkroodsma** [comment]
@bitsofbits would have insight into the priority of this.

**Comment by bitsofbits** [comment]
@redhog, @davidkroodsma : I'd say medium priority. It's important that we get that data eventually, but I'm not going to have time to do anything with it for a bit since at the moment I'm focusing on evaluating vessel classification.

**Comment by davidkroodsma** [comment]
This issue has been moved here: https://github.com/SkyTruth/GFW-Tasks/issues/236
